site_name: DataCheckr
repo_url: https://github.com/yourusername/datacheckr
nav:
  - Home: index.md
  - Usage:
      - CLI Guide: usage/cli.md
      - API Guide: usage/api.md
  - Design Decisions: design.md
  - Development:
      - Testing: dev/testing.md
      - Code Style: dev/style.md
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - codehilite
